# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Goal_pb2 as Goal__pb2


class GoalStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GoalLys = channel.unary_unary(
                '/test.Goal/GoalLys',
                request_serializer=Goal__pb2.GoalReq.SerializeToString,
                response_deserializer=Goal__pb2.GoalRes.FromString,
                )


class GoalServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GoalLys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GoalServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GoalLys': grpc.unary_unary_rpc_method_handler(
                    servicer.GoalLys,
                    request_deserializer=Goal__pb2.GoalReq.FromString,
                    response_serializer=Goal__pb2.GoalRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'test.Goal', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Goal(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GoalLys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/test.Goal/GoalLys',
            Goal__pb2.GoalReq.SerializeToString,
            Goal__pb2.GoalRes.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
