# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Goal.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Goal.proto',
  package='test',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nGoal.proto\x12\x04test\"\x1b\n\x07GoalReq\x12\x10\n\x08playerID\x18\x01 \x01(\x05\"\x19\n\x07GoalRes\x12\x0e\n\x06result\x18\x01 \x01(\t2/\n\x04Goal\x12\'\n\x07GoalLys\x12\r.test.GoalReq\x1a\r.test.GoalResb\x06proto3'
)




_GOALREQ = _descriptor.Descriptor(
  name='GoalReq',
  full_name='test.GoalReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='playerID', full_name='test.GoalReq.playerID', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=47,
)


_GOALRES = _descriptor.Descriptor(
  name='GoalRes',
  full_name='test.GoalRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='test.GoalRes.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=74,
)

DESCRIPTOR.message_types_by_name['GoalReq'] = _GOALREQ
DESCRIPTOR.message_types_by_name['GoalRes'] = _GOALRES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GoalReq = _reflection.GeneratedProtocolMessageType('GoalReq', (_message.Message,), {
  'DESCRIPTOR' : _GOALREQ,
  '__module__' : 'Goal_pb2'
  # @@protoc_insertion_point(class_scope:test.GoalReq)
  })
_sym_db.RegisterMessage(GoalReq)

GoalRes = _reflection.GeneratedProtocolMessageType('GoalRes', (_message.Message,), {
  'DESCRIPTOR' : _GOALRES,
  '__module__' : 'Goal_pb2'
  # @@protoc_insertion_point(class_scope:test.GoalRes)
  })
_sym_db.RegisterMessage(GoalRes)



_GOAL = _descriptor.ServiceDescriptor(
  name='Goal',
  full_name='test.Goal',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=76,
  serialized_end=123,
  methods=[
  _descriptor.MethodDescriptor(
    name='GoalLys',
    full_name='test.Goal.GoalLys',
    index=0,
    containing_service=None,
    input_type=_GOALREQ,
    output_type=_GOALRES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GOAL)

DESCRIPTOR.services_by_name['Goal'] = _GOAL

# @@protoc_insertion_point(module_scope)
